data:
  train_root: '../../datasets/super-resolution/T91_General100'
  test_root: '../../datasets/super-resolution/Set14'
  lr_crop_size: 16
training:
  upscale_factor: 2
  img_channels: 1 # 1 for Y, 3 for RGB
  iterations: 1000000
  batch_size: 64
  val_interval: 1000
  print_interval: 500
  checkpoint_folder: 'checkpoints'
  optimizer:
    name: adam
    lr: 1.0e-3
  scheduler:
    lr_decay: 0.5
    interval: 100000
  resume: 'None'